### ISSUE TITLE
getting this error message

### ISSUE THREAD

**Issue by Maximus48p** [JenswBE/docker-save-attachments#1]
[fetchmail -v](mv: cannot stat '/var/mail/working/new/*': No such file or directory)

This error occurs after connecting successfully to the IMAP server.

**Comment by Maximus48p** [comment]
SOLVED
The mail needs to be marked as unread/new to be fetched....

**Comment by JenswBE** [comment]
Thanks for testing my Docker build!
To be honest, I just forked the repo to contribute some improvements, but never really dived into the internals.

Maybe one day I could consider a full rewrite if it's justifiable for my usecase.
